version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - "> 8.0.5, < 9"
  - dependency-name: "@types/node"
    versions:
    - "> 14.11.10, < 15"
  - dependency-name: "@types/ws"
    versions:
    - "> 7.2.7, < 8"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: yt-search
    versions:
    - 2.7.4
    - 2.7.5
    - 2.7.6
  - dependency-name: ffmpeg-static
    versions:
    - 4.2.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
